repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.3
    hooks:
      - id: ruff-format
        args:
          - "--config=ruff.toml"

      - id: ruff
        args:
          - "--config=ruff.toml"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files # prevents giant files from being committed.
      - id: detect-private-key # detects the presence of private keys.

